# Generated by Django 4.2.1 on 2023-08-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pb_visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='pb_visualizer.rulefamily'),
        ),
    ]
