# Generated by Django 4.2.1 on 2023-08-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pb_visualizer', '0003_rename_vote_type_election_ballot_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoteType',
            new_name='BallotType',
        ),
    ]
