# Generated by Django 4.2.1 on 2023-08-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pb_visualizer', '0004_rename_votetype_ballottype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ballottype',
            options={'ordering': ['order_priority']},
        ),
    ]
